server:
  # 本地调试时使用
  port: 9081
  context-path: /i18n-server
spring: 
  application:
    name: i18n-server
  profiles:
    active: online
  
access: 
  key: rUJ4YR1nNwovLiOg
  secret: 3mQBP0rrEL2nJexMrj5VO1rt4vUbk1

registry: http://172.20.23.170:8080