server:
  # 本地调试时使用
  port: 8083    
  context-path: /rpc-server
spring: 
  application:
    name: rpc-server
  profiles:
    active: online
  
access: 
  key: rUJ4YR1nNwovLiOg
  secret: 3mQBP0rrEL2nJexMrj5VO1rt4vUbk1

registry: http://172.20.23.170:8080